package io.rong.imkit.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GROUP.
 */
public class Group {

    private Long id;
    private String ownerId;
    private String group_id;
    private String group_name;
    private String sort_key;
    private String group_nickname;
    private String user_nickname;
    private String group_type;
    private String version;
    private String introduce;
    private String bulletin;
    private String portrait_url;
    private String current_member_count;
    private String limit_member_count;
    private String create_date;
    private String is_top;

    public Group() {
    }

    public Group(Long id) {
        this.id = id;
    }

    public Group(Long id, String ownerId, String group_id, String group_name, String sort_key, String group_nickname, String user_nickname, String group_type, String version, String introduce, String bulletin, String portrait_url, String current_member_count, String limit_member_count, String create_date, String is_top) {
        this.id = id;
        this.ownerId = ownerId;
        this.group_id = group_id;
        this.group_name = group_name;
        this.sort_key = sort_key;
        this.group_nickname = group_nickname;
        this.user_nickname = user_nickname;
        this.group_type = group_type;
        this.version = version;
        this.introduce = introduce;
        this.bulletin = bulletin;
        this.portrait_url = portrait_url;
        this.current_member_count = current_member_count;
        this.limit_member_count = limit_member_count;
        this.create_date = create_date;
        this.is_top = is_top;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId;
    }

    public String getGroup_id() {
        return group_id;
    }

    public void setGroup_id(String group_id) {
        this.group_id = group_id;
    }

    public String getGroup_name() {
        return group_name;
    }

    public void setGroup_name(String group_name) {
        this.group_name = group_name;
    }

    public String getSort_key() {
        return sort_key;
    }

    public void setSort_key(String sort_key) {
        this.sort_key = sort_key;
    }

    public String getGroup_nickname() {
        return group_nickname;
    }

    public void setGroup_nickname(String group_nickname) {
        this.group_nickname = group_nickname;
    }

    public String getUser_nickname() {
        return user_nickname;
    }

    public void setUser_nickname(String user_nickname) {
        this.user_nickname = user_nickname;
    }

    public String getGroup_type() {
        return group_type;
    }

    public void setGroup_type(String group_type) {
        this.group_type = group_type;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getIntroduce() {
        return introduce;
    }

    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    public String getBulletin() {
        return bulletin;
    }

    public void setBulletin(String bulletin) {
        this.bulletin = bulletin;
    }

    public String getPortrait_url() {
        return portrait_url;
    }

    public void setPortrait_url(String portrait_url) {
        this.portrait_url = portrait_url;
    }

    public String getCurrent_member_count() {
        return current_member_count;
    }

    public void setCurrent_member_count(String current_member_count) {
        this.current_member_count = current_member_count;
    }

    public String getLimit_member_count() {
        return limit_member_count;
    }

    public void setLimit_member_count(String limit_member_count) {
        this.limit_member_count = limit_member_count;
    }

    public String getCreate_date() {
        return create_date;
    }

    public void setCreate_date(String create_date) {
        this.create_date = create_date;
    }

    public String getIs_top() {
        return is_top;
    }

    public void setIs_top(String is_top) {
        this.is_top = is_top;
    }

}
