package io.rong.imkit.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GROUP_MEMBER.
 */
public class GroupMember {

    private Long id;
    private String user_id;
    private String group_nickname;
    private String user_nickname;
    private String sort_key;
    private String group_id;
    private String portrait_url;
    private String owner_id;
    private String identity;

    public GroupMember() {
    }

    public GroupMember(Long id) {
        this.id = id;
    }

    public GroupMember(Long id, String user_id, String group_nickname, String user_nickname, String sort_key, String group_id, String portrait_url, String owner_id, String identity) {
        this.id = id;
        this.user_id = user_id;
        this.group_nickname = group_nickname;
        this.user_nickname = user_nickname;
        this.sort_key = sort_key;
        this.group_id = group_id;
        this.portrait_url = portrait_url;
        this.owner_id = owner_id;
        this.identity = identity;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getGroup_nickname() {
        return group_nickname;
    }

    public void setGroup_nickname(String group_nickname) {
        this.group_nickname = group_nickname;
    }

    public String getUser_nickname() {
        return user_nickname;
    }

    public void setUser_nickname(String user_nickname) {
        this.user_nickname = user_nickname;
    }

    public String getSort_key() {
        return sort_key;
    }

    public void setSort_key(String sort_key) {
        this.sort_key = sort_key;
    }

    public String getGroup_id() {
        return group_id;
    }

    public void setGroup_id(String group_id) {
        this.group_id = group_id;
    }

    public String getPortrait_url() {
        return portrait_url;
    }

    public void setPortrait_url(String portrait_url) {
        this.portrait_url = portrait_url;
    }

    public String getOwner_id() {
        return owner_id;
    }

    public void setOwner_id(String owner_id) {
        this.owner_id = owner_id;
    }

    public String getIdentity() {
        return identity;
    }

    public void setIdentity(String identity) {
        this.identity = identity;
    }

}
